# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- dev

pool:
  vmImage: windows-latest

parameters:
  - name: browser
    type: string
    default: Chrome
    values:
    - Chrome
    - Firefox
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install -X -Dbrowser=${{parameters.browser}}'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml' 

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
  inputs:    
    Contents: 'test-output\**'
    TargetFolder: $(build.artifactstagingdirectory)
    OverWrite: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
  inputs:    
    Contents: 'Reports\**'
    TargetFolder: $(build.artifactstagingdirectory)    

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)